# Generated by Django 6.0.3 on 2026-03-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('statusConta', models.CharField(default='Pendente', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AreaComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('prazoCancelamentoDias', models.IntegerField()),
                ('tempoDaReserva', models.IntegerField(help_text='Tempo em horas')),
                ('statusLocal', models.CharField(choices=[('Disponivel', 'Disponível'), ('EmManutencao', 'Em Manutenção'), ('Ocupado', 'Ocupado')], default='Disponivel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('statusConta', models.CharField(default='Pendente', max_length=50)),
                ('bloco', models.CharField(max_length=10)),
                ('apartamento', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sindico',
            fields=[
                ('administrador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='condominio_reservas.administrador')),
            ],
            options={
                'abstract': False,
            },
            bases=('condominio_reservas.administrador',),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataReserva', models.DateField()),
                ('horarioInicio', models.TimeField()),
                ('horarioFim', models.TimeField()),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('areaComum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio_reservas.areacomum')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio_reservas.morador')),
            ],
        ),
    ]
