# Generated by Django 5.0.14 on 2026-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='statusConta',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado'), ('Desabilitado', 'Desabilitado')], default='Pendente', max_length=50),
        ),
    ]
