# Generated by Django 5.0.14 on 2026-04-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_reservas', '0002_alter_usuario_statusconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomum',
            name='tempoDaReserva',
            field=models.IntegerField(),
        ),
    ]
