# Generated by Django 5.0.14 on 2026-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_reservas', '0003_alter_areacomum_tempodareserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomum',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
