# Generated by Django 5.0.14 on 2026-05-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_reservas', '0004_alter_areacomum_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sindico',
            options={'verbose_name': 'Sindico', 'verbose_name_plural': 'Sindicos'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='areacomum',
            name='statusLocal',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('EmManutencao', 'Em Manutencao')], default='Disponivel', max_length=20),
        ),
    ]
