# Generated by Django 5.0.14 on 2026-06-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_reservas', '0005_alter_sindico_options_reserva_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado Sem Custos'), ('Cancelado_Multa', 'Cancelado com Multa')], default='Pendente', max_length=50),
        ),
    ]
